import{a as m,S as p,i as s}from"./assets/vendor-lDhL-8I6.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const g="49778514-c989ee5c1575b477a31bb7b72",y="https://pixabay.com/api/";async function h(i){const t={key:g,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await m.get(y,{params:t})).data.hits}const c=document.querySelector(".gallery"),l=document.querySelector(".loader"),L=new p(".gallery a",{captionsData:"alt",captionDelay:250});function b(){const i=document.querySelectorAll(".gallery img"),t=i.length;let o=0;return new Promise(n=>{i.forEach(e=>{e.addEventListener("load",()=>{o+=1,o===t&&n()})})})}function v(i){const t=i.map(({webformatURL:o,largeImageURL:n,tags:e,likes:r,views:a,comments:d,downloads:f})=>`<li class="gallery-item">
            <a href="${n}">
              <img src="${o}" alt="${e}" loading="lazy"/>
            </a>
            <div class="info">
              <p> ${r}</p>
              <p> ${a}</p>
              <p> ${d}</p>
              <p> ${f}</p>
            </div>
          </li>`).join("");c.insertAdjacentHTML("beforeend",t),L.refresh()}function w(){c.innerHTML=""}function S(){l.classList.add("visible")}function q(){l.classList.remove("visible")}const u=document.querySelector(".form"),P=u.querySelector('input[name="search-text"]');u.addEventListener("submit",i=>{i.preventDefault();const t=P.value.trim();if(!t){s.warning({message:"Please enter a search term.",position:"topRight"});return}w(),S(),h(t).then(o=>{if(o.length===0)throw s.info({message:`Sorry, there are no images matching "${t}". Please try again!`,position:"topRight"}),new Error("No images found");return v(o),b()}).catch(o=>{o.message!=="No images found"&&s.error({message:"Something went wrong. Please try again later.",position:"topRight"})}).finally(()=>{q()})});
//# sourceMappingURL=index.js.map
